### ISSUE TITLE
Minitest 5.6.1 breaks minitest-rspec_mocks

### ISSUE THREAD

**Issue by mvz** [codeodor/minitest-rspec_mocks#4]
Minitest 5.6 introduces `expect` in its `minitest/spec` syntax, and due to some moving around of methods, this now takes precedence over the `expect` introduces by rspec-mocks. Hence, this now breaks:

```ruby
describe 'foo' do
  it 'bar' do
    expect(baz).to receive(:quux)
  end
end
```

This results in:
```
NoMethodError: undefined method `to' for #<Minitest::Expectation:0x007f17b6548600>
```

**Comment by codeodor** [comment]
Thanks for the heads up! I hadn't upgraded yet.

I'll try my best to get to it this week, but I have some personal plans coming up that may prevent me from working on it until the week of  May 18th.

**Comment by mvz** [comment]
No problem, I've downgraded minitest for now as a work-around in my tests.

**Comment by codeodor** [comment]
@mvz Do you have any more info on how to reproduce this? I ran the tests that [are supposed to be exercising this behavior](https://github.com/codeodor/minitest-rspec_mocks/blob/master/test/minitest/rspec_mocks_test.rb#L38-L46) with Minitest 5.6.0 and 5.6.1 and both still work for me.

Maybe I need to try with your same Ruby and RSpec/RSpec-Mocks versions too?

**Comment by mvz** [comment]
The problem only shows up when using `describe` blocks. I've added such a block in #5 to demonstrate the problem.

**Comment by codeodor** [comment]
Awesome, thanks! :+1: I've got to present at a career day this morning, but I should be able to work on it this afternoon.

**Comment by codeodor** [comment]
As it turns out I couldn't get to it today, but it's still on my radar for this week. Sorry :frowning:

**Comment by mvz** [comment]
No problem at all.

I just noticed that it isn't particularly clear from my report, but things are fine with minitest 5.6.0.

**Comment by codeodor** [comment]
Thanks for understanding. I just hate not getting around to it in a timely fashion. =)

**Comment by codeodor** [comment]
@mvz Would you mind checking your project against the `minitest-5.6.1` branch here? I fixed the test you added, but I want to be sure it's gonna work in a more diverse environment before releasing a new version.

Thanks!

**Comment by mvz** [comment]
@codeodor works like a charm, thanks!

**Comment by codeodor** [comment]
Awesome, *thank you* for reporting the problem and making the failing test. It was a huge help!

I pushed v0.3.0 to RubyGems to fix this.

**Comment by mvz** [comment]
Thanks for fixing!
